spring.application.name=searchconsole

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8081

spring.datasource.url=jdbc:postgresql://ep-ancient-unit-ao9m5n60-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_dNWt5eIRwxo8&sslmode=require&channelBinding=require
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable JDBC Batching
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true